---
- hosts: mywebserver
  become: yes
  tasks:
     - name: i want to run command on ansible node
       command: hostnameee -f
       register: myResult

     - name: i want to display result of linux command
       debug: 
         msg: "{{myResult}}"  