--- 
- hosts: mywebserver
  becomes: yes
  vars:
      myvar1: git
      myvar2: tree
      myvar3: wget

  tasks: 
       - name: i want to display value of the vars
         debug:
           msg: "{{myvar1}}"    